@startuml

top to bottom direction

!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(user, "User", "A user of Standard bank service")
Person(backOfficeStaff, "Back Office Staff", "Worker in a back office")
Person(frontOfficeStaff, "Front Office Staff", "Worker in a front office")
Person(callCenterStaff, "Call Center Staff", "Worker in a call center")

System(standartBankSystem, "Standart Bank System")
System_Ext(callCenterSystem, "Call center system", "External call center system")
System_Ext(telecom, "Telekom operator", "External telecom operator")

Container_Boundary(standartBankSystem, "Standart Bank System") {
    Container(api, "Users API", "Kong", "API Gateway for the bank clients")
    Container(apiBack, "Back office API", "Kong", "API Gateway for back office workers")
    Container(apiFront, "Front office API", "Kong", "API Gateway for front office workers")
    Container(apiCallCenter, "Call Center API", "Kong", "API Gateway for call center workers")

    Container(onlineBanking, "ABC banking system", "ASP.NET MVC 4.5, MS SQL", "Support debit card operations")
    Container(bankingSystem, "ABC banking system", "Oracle", "A core system of the bank")
    Container(callCenterCrm, "Call Center CRM", "Java Spring Boot, PostgreSQL", "CRM sysytem for call centers")
    Container(operatorGateway, "Operator Gateway", "Java Spring Boot, PostgreSQL", "CRM sysytem for call centers")
}

Rel(user, api, HTTP)
Rel(backOfficeStaff, apiBack, HTTP)
Rel(frontOfficeStaff, apiFront, HTTP)
Rel(callCenterStaff, apiCallCenter, HTTP)

Rel(api, onlineBanking, call)
Rel(apiBack, bankingSystem, call)
Rel(apiFront, onlineBanking, call)
Rel(apiCallCenter, callCenterCrm, call)
Rel(apiCallCenter, callCenterSystem, HTTP)

Rel(onlineBanking, bankingSystem, HTTP)
Rel(onlineBanking, callCenterCrm, HTTP)
Rel(onlineBanking, operatorGateway, HTTP)
Rel(operatorGateway, onlineBanking, HTTP)

Rel(operatorGateway, telecom, "HTTP")
Rel(telecom, operatorGateway, "HTTP")

